---
title: "Cytof Analysis using reclustered data, final CIR resubmission"
author: "Mari Nakazawa"
date: "2024-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependencies

```{r}
library(tidyverse)
library(MKinfer)
library(knitr)
library(RColorBrewer)
library(conflicted)
library(ggpubr)
library(patchwork)
library(ComplexHeatmap)
conflicts_prefer(dplyr::filter)
```

## Clinical data

```{r, echo = FALSE}
clinical_cohort <- read_csv("../Data/patients_list_final.csv") %>% 
        select(-`...1`)
```

## Load CyTOF data

```{r cytof data, echo = FALSE}
cytof3 <- read_csv("../Data/cytof_final.csv") %>% 
        select(-`...1`)
```

## Merged cytof and timepoint data

```{r, echo = FALSE}
cytof_paired <- cytof3 %>% 
        group_by(patient) %>%
        filter(
    # Keep patients with at least one baseline and one on-treatment specimen
                any(timepoint == 0) & any(timepoint %in% c(1, 2))) %>%
        filter(
    # Keep baseline (0) and the earliest on-treatment specimen (1 or 2)
                timepoint == 0 | (timepoint %in% c(1, 2) & timepoint == min(timepoint[timepoint %in% c(1, 2)]))) %>%
        ungroup() %>% 
        mutate(timepoint = recode(timepoint, "0" = "Baseline", "1" = "On Treatment", "2" = "On Treatment")) 

long_cytof <- cytof_paired %>% 
        pivot_longer(cols = -c("patient", "timepoint"), names_to = "cell_type", values_to = "counts") %>%
        mutate(counts = as.numeric(counts) + 1e-6) %>% 
        mutate(log2_counts = log2(counts)) %>% 
        left_join(clinical_cohort) 
```

## Distributions by cell type

```{r}
#Untransformed data by cell type (cell proportion)
ggplot(long_cytof, aes(x = counts)) +
        geom_histogram() +
        theme_classic() +
        facet_wrap(~cell_type, ncol = 6)

#Log-transformed and scaled data by cell type
ggplot(long_cytof, aes(x = log2_counts)) +
        geom_histogram() +
        theme_classic() +
        facet_wrap(~cell_type, ncol = 6)
```

## Boxplot, fold change

```{r boxplot fold change, echo = FALSE}
wide_cytof <- long_cytof %>% 
        select(-log2_counts) %>% 
        pivot_wider(names_from = timepoint, values_from = counts) %>% 
        mutate(fold_change = `On Treatment`/Baseline) %>% 
        filter(!is.na(fold_change)) %>% 
        mutate(log2_fc = log2(`On Treatment`/Baseline))

length(unique(wide_cytof$patient)) #88

ggplot(wide_cytof, aes(x = anti_ctla4, y = log2_fc, color = anti_ctla4)) +
        geom_boxplot(lwd = 1) +
        geom_jitter() +
        theme_classic() +
        theme(legend.position = "none") +
        scale_color_brewer(palette = "Dark2") +
        scale_x_discrete(labels = c("Single ICI", "Combination ICI")) +
        labs(x = "Regimen", y = "Log2 fold change immune cell count") +
        stat_compare_means(method = "wilcox.test", size = 4.5) +
        facet_wrap(~cell_type, scales = "free_y", ncol = 5)
```

## Plot with facet wrap

```{r}
select_cells <- wide_cytof %>% 
        filter(cell_type %in% c("Th17", "Treg")) %>% 
        ggplot(aes(x = anti_ctla4, y = log2_fc, color = anti_ctla4)) + 
        geom_boxplot(lwd = 1) +
        geom_jitter() +
        theme_classic() +
        theme(legend.position = "none") +
        scale_color_brewer(palette = "Dark2") +
        scale_x_discrete(labels = c("Single ICI", "Combination ICI")) +
        labs(x = "Regimen", y = "Log2 fold change cell count") +
        stat_compare_means(method = "wilcox.test") +
        facet_wrap(~cell_type, ncol = 4, scales = "free_y")

select_cells
```

## Simple linear regression (on fold change)

```{r simple linear regression, echo = FALSE}
model_results <- list()
model_betas <- vector()

for(i in unique(wide_cytof$cell_type)){
        
        d_cytof <- wide_cytof %>% 
                filter(cell_type == i) %>% 
                mutate(cancer_type = recode(cancer_type, "Head and Neck" = "Other", "Lung" = "Other", "Cutaneous" = "Other", "Endocrine" = "Other", "Sarcoma" = "Other", "Gyn" = "Other")) %>% 
                mutate(prior_tx = ifelse(treatment_summary == "neither", FALSE, TRUE)) %>% 
                mutate(msi = ifelse(msi_tmb_hi == TRUE, "High", "Low"))
                
        d_cytof$Gender <- factor(d_cytof$Gender, levels = c("Female", "Male"))
        d_cytof$cancer_type <- factor(d_cytof$cancer_type, levels = c("GI", "GU", "Other"))
        d_cytof$msi <- factor(d_cytof$msi, levels = c("Low", "High"))
        d_cytof$prior_tx <- factor(d_cytof$prior_tx, levels = c(FALSE, TRUE))
        d_cytof$anti_ctla4 <- factor(d_cytof$anti_ctla4, levels = c(FALSE, TRUE))
        d_cytof$responder <- factor(d_cytof$responder, levels = c(FALSE, TRUE))
        
        linear_model <- lm(log2_fc ~ `Age On Study` + Gender + cancer_type + anti_ctla4 + prior_tx + msi + responder, data = d_cytof)
        
        model_results[[i]] = linear_model
        
        temp <- summary(model_results[[i]])
        d_rows <- as.data.frame(temp$coefficients[2:9, ]) %>% 
                mutate(cell_type = i) %>% 
                mutate(variable = c("age", "gender_male", "cancer_gu", "cancer_other", "combo_ICI", "prior_tx", "mut", "responder"))
        
        model_betas <- rbind(model_betas, d_rows)
        
}

linear_m <- as.data.frame(model_betas) %>% 
        select(Estimate, `Pr(>|t|)`, cell_type, variable) %>% 
        rename(beta = Estimate, nominal_p = `Pr(>|t|)`) %>% 
        group_by(variable) %>% 
        mutate(nominal_p = as.numeric(nominal_p), p_adjust = p.adjust(nominal_p, "BY")) %>% 
        arrange(p_adjust) 

head(linear_m, 20)
```

## Extract coefficients

```{r}
model_summary <- summary(model_results[["Treg"]])
coefficients <- model_summary$coefficients
results_df <- as.data.frame(coefficients)
colnames(results_df) <- c("Estimate", "Std. Error", "t value", "p value")
results_df <- results_df[, c("Estimate", "Std. Error", "p value")]

results <- linear_m %>% 
        filter(cell_type %in% c("Treg"))
```

## Th17:Treg ratios

```{r}
ratios <- long_cytof %>% 
        filter(cell_type == "Th17" | cell_type == "Treg") %>% 
        select(patient, timepoint, anti_ctla4, cell_type, counts) %>% 
        pivot_wider(id_cols = c("patient", "timepoint", "anti_ctla4"), names_from = cell_type, values_from = counts) %>% 
        mutate(log2_th17_treg = log2(Th17/Treg))

#Ratios
ratio_figs <- ratios %>% 
        ggplot(aes(x = anti_ctla4, y = log2_th17_treg, color = anti_ctla4)) +
        geom_boxplot(lwd = 1) +
        geom_jitter() +
        theme_classic() +
        theme(legend.position = "none") +
        scale_color_brewer(palette = "Dark2") +
        scale_x_discrete(labels = c("Single ICI", "Combination ICI")) +
        labs(x = "Regimen", y = "Log2 Th17:Treg ratio") +
        stat_compare_means(method = "wilcox.test") +
        facet_wrap(~timepoint)

ratio_figs
```

# Session info

```{r}
devtools::session_info()
```

This document was processed on: `r Sys.Date()`.